default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "PictureThis.xcodeproj")
    build_app(workspace: "PictureThis.xcworkspace", scheme: "PictureThis")
    upload_to_testflight
  end
end
